language: ruby

rvm:
  - 2.3.1

sudo: false

env:
  global:
    - LOGIN_DB_USER=postgres
    - LOGIN_SECRET_TOKEN=123abc
    - TEST_TWITTER_USERNAME=libtechnyu
    - ALEPH_HOST=aleph.library.edu
    - ALEPH_LIBRARY=ALEPH
    - ALEPH_SUB_LIBRARY=BET
    - SHIBBOLETH_LOGOUT_URL=https://aqa.home.nyu.edu/sso/UI/Logout
    - PDS_URL=https://pdsdev.library.nyu.edu
    - BOBCAT_URL=http://bobcatdev.library.nyu.edu

before_install:
  - bundle config --local github.https true

before_script:
  - psql -c 'create database login_test;' -U $LOGIN_DB_USER
  - bundle exec rake db:schema:load RAILS_ENV=test

notifications:
  email:
    - lib-webservices@nyu.edu

cache: bundler
