version: '3.7'
x-volumes: &default-volumes
  volumes:
    - ./lib:/app/lib/
    - ./app:/app/app/
    - ./spec:/app/spec/
    - ./features:/app/features/
    - ./screenshots:/screenshots/
    - ./tmp/:/app/tmp/

x-production: &production-image
  build:
    context: .
    cache_from:
    - login
    - $IMAGES_DOMAIN/login
    - $IMAGES_DOMAIN/login:$BRANCH_NO_SLASH
  image: login:latest

x-development: &development-image
  build:
    context: .
    cache_from:
    - login_test
    - $IMAGES_DOMAIN/login_test
    - $IMAGES_DOMAIN/login_test:$BRANCH_NO_SLASH
    dockerfile: Dockerfile.test
    args:
      AQUA_MICROSCANNER_TOKEN:
  image: login_test:latest

x-dev-env: &dev-env
  environment:
    RAILS_ENV: development
  env_file:
    - test.env

services:
  dev:
    <<: *development-image
    ports:
      - "3000:3000"
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rails server -b 0.0.0.0
    depends_on:
      - setup_dev_dbs
    <<: *dev-env
    # <<: *default-volumes

  test:
    <<: *development-image
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake
    depends_on:
      - setup_test_dbs
    <<: *dev-env
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
      SCREENSHOT_FAILURES: "true"
    # <<: *default-volumes

  setup_dev_dbs:
    <<: *development-image
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake db:setup
    depends_on:
      - db
    <<: *dev-env

  setup_test_dbs:
    <<: *development-image
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake db:setup
    depends_on:
      - db
    <<: *dev-env
    environment:
      RAILS_ENV: test

  db:
    image: postgres:alpine
    expose:
      - "5432"

  # Use below settings for testing unicorn image locally
  unicorn:
    <<: *production-image
    ports:
      - "5000:5000"
    environment:
      UNICORN_PORT: 5000
      #UNICORN_WEB_CONCURRENCY: 1
      #UNICORN_LOG_LEVEL: "debug"
      #env_file:
      #en- .env
    # <<: *default-volumes
    depends_on:
      - setup_dev_dbs
