version: '3.7'
x-volumes: &default-volumes
  volumes:
    - ./lib:/app/lib/
    - ./app:/app/app/
    - ./spec:/app/spec/
    - ./features:/app/features/
    - ./screenshots:/screenshots/
    - ./tmp/:/app/tmp/

x-production: &production-build
  build:
    context: .
    cache_from:
    - login
    - $IMAGES_DOMAIN/login
    - $IMAGES_DOMAIN/login:$BRANCH_NO_SLASH
  image: login:latest

x-development: &development-build
  build:
    context: .
    cache_from:
    - login_test
    - $IMAGES_DOMAIN/login_test
    - $IMAGES_DOMAIN/login_test:$BRANCH_NO_SLASH
    dockerfile: Dockerfile.test
    args:
      AQUA_MICROSCANNER_TOKEN:
  image: login_test:latest

x-dev-env: &dev-env
  environment:
    RAILS_ENV: development
    DOCKER: "true"
  env_file:
    - test.env


services:
  dev:
    <<: *development-build
    ports:
      - "3000:3000"
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rails server -b 0.0.0.0
    depends_on:
      - setup_dev_dbs
    <<: *dev-env
    # <<: *default-volumes

  setup_dev_dbs:
    <<: *development-build
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake db:setup
    depends_on:
      - db
    <<: *dev-env

  test:
    <<: *development-build
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake
    depends_on:
      - setup_test_dbs
    <<: *dev-env
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
      SCREENSHOT_FAILURES: "true"
    # <<: *default-volumes

  setup_test_dbs:
    <<: *development-build
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake db:setup
    depends_on:
      - db
    <<: *dev-env
    environment:
      RAILS_ENV: test

  unicorn:
    <<: *production-build
    ports:
      - "5000:5000"
    environment:
      UNICORN_PORT: 5000
      UNICORN_WEB_CONCURRENCY: 2
      LOG_LEVEL: "debug"
      DOCKER: "true"
    # Use below settings when testing unicorn image locally
    #   USE_PRODUCTION_ASSETS: "true" # necessary otherwise stack level too deep
    # depends_on:
    #   - setup_dev_dbs
    # <<: *dev-env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - unicorn

  db:
    image: postgres:alpine
    expose:
      - "5432"
