version: '3.2'
services:

  dev:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - test.env
    environment:
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    command: ["./wait-for-it.sh", "db:5432", "--", "tail -f", "/dev/null"]
    depends_on:
      - setup_dbs

  test:
    build: .
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["./wait-for-it.sh", "db:5432", "--", "tail -f", "/dev/null"]
    depends_on:
      - setup_test_dbs

  setup_test_dbs:
    build: .
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["./wait-for-it.sh", "db:5432", "--", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    build: .
    env_file:
      - test.env
    command: ["./wait-for-it.sh", "db:5432", "--", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: postgres:alpine
    expose:
      - "5432"
