version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - RAILS_ENV=test
      - LOGIN_DB_USER=postgres
      - LOGIN_DB_HOST=db
      - LOGIN_DB_DATABASE=login_test
      - LOGIN_SECRET_TOKEN=123abc
      - TEST_TWITTER_USERNAME=libtechnyu
      - ALEPH_HOST=aleph.library.edu
      - ALEPH_LIBRARY=ALEPH
      - ALEPH_SUB_LIBRARY=BET
      - SHIBBOLETH_LOGOUT_URL=https://aqa.home.nyu.edu/sso/UI/Logout
      - PDS_URL=https://pdsdev.library.nyu.edu
      - BOBCAT_URL=http://bobcatdev.library.nyu.edu
