FROM quay.io/nyulibraries/selenium_chrome_headless_ruby:2.5.7-slim-chrome_79

ENV DOCKER true
ENV INSTALL_PATH /app
ENV BUNDLE_PATH /usr/local/bundle

#RUN groupadd -g 2000 docker -r && \
#  useradd -u 1000 -r --no-log-init -m -d $INSTALL_PATH -g docker docker

# Installs dependencies to image (since test image, leave installed)
USER root
COPY --chown=docker:docker Gemfile Gemfile.lock ./
ARG RUN_PACKAGES="git libfontconfig libfreetype6 libpq-dev zlib1g-dev build-essential"
ARG BUILD_PACKAGES="gnupg2"
RUN apt-get update -qq && apt-get -y --no-install-recommends install $RUN_PACKAGES $BUILD_PACKAGES \
      #  && apt-get install -y gnupg2 curl && curl -sL https://deb.nodesource.com/setup_8.x | bash -  \
      #  && apt-get install -y nodejs \
      #  && apt-get autoremove gnupg2 curl --purge -y \
  && wget https://deb.nodesource.com/setup_10.x | bash - \
  && apt-get -y --no-install-recommends install nodejs npm \
  && wget --no-check-certificate -q -O - https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /tmp/wait-for-it.sh \
  && chmod a+x /tmp/wait-for-it.sh \
  && gem install bundler -v '2.0.2' \
  && bundle config --global github.https true \ 
  && bundle install --without no_docker --jobs 20 --retry 5 \ 
  && chown -R docker:docker /usr/local/bundle \
  && chown -R docker:docker $INSTALL_PATH \
  && apt-get --purge -y autoremove $BUILD_PACKAGES
RUN npm install -g yarn

WORKDIR $INSTALL_PATH
USER docker

RUN bundle config github.https true

COPY --chown=docker:docker . .
# Copy compass-core deprecation manual fix
COPY ./vendor/gems/compass-core-1.0.3/ $BUNDLE_PATH/gems/compass-core-1.0.3/
RUN RAILS_ENV=development bundle exec rake assets:precompile

EXPOSE 3000

