version: '3.2'
services:

  dev:
    build:
      context: .
    image: login:latest
    # volumes:
    #   - ./vendor:/app/vendor
    #   - ./lib:/app/lib/
    #   - ./app:/app/app/
    ports:
      - "3000:3000"
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:5432", "--", "bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV:
    depends_on:
      - setup_dbs

  test:
    build:
      context: .
    image: login:latest
    env_file:
      - test.env
    environment:
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
      RAILS_ENV: test
      SCREENSHOT_FAILURES: "true"
    command: ["/tmp/wait-for-it.sh", "db:5432", "--", "bundle", "exec", "rake"]
    depends_on:
      - setup_test_dbs
    # volumes:
      # - ./lib:/app/lib/
      # - ./app:/app/app/
      # - ./spec:/app/spec/
      # - ./features:/app/features/
      # - ./screenshots:/screenshots/

  setup_test_dbs:
    build:
      context: .
    image: login:latest
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:5432", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    build:
      context: .
    image: login:latest
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:5432", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: postgres:alpine
    expose:
      - "5432"
