version: '3.7'
x-volumes: &default-volumes
  volumes:
    - ./lib:/app/lib/
    - ./app:/app/app/
    - ./spec:/app/spec/
    - ./features:/app/features/
    - ./screenshots:/screenshots/
    - ./tmp/:/app/tmp/

x-production: &production-image
  build:
    context: .
    cache_from:
    - login
    - quay.io/nyulibraries/login
    - quay.io/nyulibraries/login:$BRANCH_NO_SLASH
  image: login:latest

x-development: &development-image
  build:
    context: .
    cache_from:
    - login_test
    - quay.io/nyulibraries/login_test
    - quay.io/nyulibraries/login_test:$BRANCH_NO_SLASH
    dockerfile: Dockerfile.test
  image: login_test:latest

services:
  dev:
    <<: *development-image
    ports:
      - "3000:3000"
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rails server -b 0.0.0.0
    depends_on:
      - setup_dev_dbs
        #  - memcached
    env_file:
      - test.env
    environment:
      RAILS_ENV: development 
    # <<: *default-volumes

  test:
    <<: *development-image
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake
    depends_on:
      - setup_test_dbs
    env_file:
      - test.env
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
      SCREENSHOT_FAILURES: "true"
    # <<: *default-volumes

  setup_dev_dbs:
    <<: *development-image
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake db:setup
    depends_on:
      - db
    env_file:
      - test.env
    environment:
      RAILS_ENV: development

  setup_test_dbs:
    <<: *development-image
    command: /tmp/wait-for-it.sh db:5432 -- bundle exec rake db:setup
    depends_on:
      - db
    env_file:
      - test.env
    environment:
      RAILS_ENV: test

  db:
    image: postgres:alpine
    expose:
      - "5432"

  memcached:
    image: memcached:alpine

  # Use below settings for testing unicorn image locally
  unicorn:
    <<: *production-image
    command: ["./script/start.sh", "production"]
    ports:
      - "5000:5000"
    env_file:
      - test.env
    environment:
      UNICORN_PORT: 5000
      LOGIN_DB_DATABASE: login_development
      RAILS_LOG_LEVEL: debug
    depends_on:
      - setup_dev_dbs
      - memcached
  
  shibboleth:
    image: quay.io/nyulibraries/login_shibboleth:master
    ports:
      - "8080:8080"

  nginx:
    image: quay.io/nyulibraries/nginx:1.15.8-0
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9292:9292"
    depends_on:
      - unicorn
      - shibboleth
