version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./script/docker_test
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - LOGIN_DB_HOST=db
