FROM nyulibraries/selenium_chrome_headless_ruby:2.5.1-slim-chrome_69

ENV INSTALL_PATH /app
ENV BUNDLE_PATH /usr/local/bundle

ARG RUN_PACKAGES="git libfontconfig libfreetype6 libpq-dev nodejs"
ARG BUILD_PACKAGES="build-essential zlib1g-dev wget"

# Use if rapidly changing gems to avoid reinstall
# RUN apt-get update -qq \
#   && apt-get -y --no-install-recommends install $RUN_PACKAGES $BUILD_PACKAGES

RUN groupadd -g 2000 docker -r && \
  useradd -u 1000 -r --no-log-init -m -d $INSTALL_PATH -g docker docker

WORKDIR $INSTALL_PATH

# Install gems in cachable way
COPY Gemfile Gemfile.lock ./
RUN bundle config --global github.https true
RUN wget --no-check-certificate -q -O - https://cdn.rawgit.com/vishnubob/wait-for-it/master/wait-for-it.sh > /tmp/wait-for-it.sh && chmod a+x /tmp/wait-for-it.sh \
  && apt-get update -qq \
  && apt-get -y --no-install-recommends install $RUN_PACKAGES $BUILD_PACKAGES \
  && gem install bundler \
  && bundle install --without no_docker,production --jobs 20 --retry 5 \
  && apt-get remove --purge -y $BUILD_PACKAGES

# Copy compass-core deprecation manual fix
COPY ./vendor/gems/compass-core-1.0.3/ $BUNDLE_PATH/gems/compass-core-1.0.3/
# Copy source into container
COPY . .
# Precompiles asset for faster testing and development
RUN DOCKER=true RAILS_ENV=development bundle exec rake assets:precompile