docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.24.1-0
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build test
      docker-compose build unicorn

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      script/docker/pull_docker.sh

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      script/docker/push_docker.sh

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io

hermes_deploy: &hermes_deploy
  run:
    name: Deploy via Hermes
    command: |
      export TAG=${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master setImage -deployment=login-unicorn -tag=$TAG
      timeout 1m sh -c 'until docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master rolloutStatus -deployment=login-unicorn -wait=false; do sleep 5; done'

version: 2
jobs:
  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *auth_quay
      - run:
          name: Run tests
          command: docker-compose run test
      - <<: *push_docker


  deploy-dev:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - <<: *auth_quay
      - run:
          name: Curl on-prem Jenkins
          command: |
            docker run appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Login/job/Login%20Development%20Deploy/build/api
      - run:
          name: Export Hermes Dev env vars
          command: |
            echo 'export HERMES_HOST=https://hermes-dev.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_DEV' >> $BASH_ENV
      - <<: *hermes_deploy

  deploy-prod:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - <<: *auth_quay
      - run:
          name: Curl on-prem Jenkins
          command: |
            docker run appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Login/job/Login%20Production%20Deploy/build/api
      - run:
          name: Export Hermes Prod env vars
          command: |
            echo 'export HERMES_HOST=https://hermes.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_PROD' >> $BASH_ENV
      - <<: *hermes_deploy

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
              - test
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          requires:
              - test
          filters:
            branches:
              only: master
