docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build test
      docker-compose build unicorn

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      script/docker/pull_docker.sh

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      script/docker/push_docker.sh

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io

version: 2
jobs:
  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *auth_quay
      - run:
          name: Run tests
          command: docker-compose run test
      - <<: *push_docker

  deploy-dev:
    docker:
      - image: appropriate/curl
    steps:
      - run:
          name: Deploy into staging via Jenkins
          command: |
            curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Login/job/Login%20Development%20Deploy/build/api
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            curl -u $JENKINS_STAGE_USERNAME:$JENKINS_STAGE_API_KEY -X POST https://jenkinsapi-dev.library.nyu.edu/job/Login%20Development%20Deploy/build/api --data-urlencode json="{\"parameter\": [{\"name\":\"TAG\", \"value\":\"${BRANCH_NO_SLASH}-${CIRCLE_SHA1}\"}]}"

  deploy-prod:
    docker:
      - image: appropriate/curl
    steps:
      - run:
          name: Deploy into production via Jenkins
          command: |
            curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Login/job/Login%20Production%20Deploy/build/api
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            curl -u $JENKINS_PROD_USERNAME:$JENKINS_PROD_API_KEY -X POST https://jenkinsapi.library.nyu.edu/job/Login%20Production%20Deploy/build/api --data-urlencode json="{\"parameter\": [{\"name\":\"TAG\", \"value\":\"${BRANCH_NO_SLASH}-${CIRCLE_SHA1}\"}]}"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
              - test
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          requires:
              - test
          filters:
            branches:
              only: master
