version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/login
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start container and run tests
          command: |
            docker-compose run -e RAILS_ENV=test web rake
