# Private institutional settings
<% if ENV.has_key?("INSTITUTIONS") && !(Rails.env.test? || ENV["DOCKER"]) %>
<%= Figs.env.institutions.to_yaml %>
<% else %>
---
# Some default IPs for testing off-campus functionality
NYUAD:
  ip_addresses:
    - 127.0.0.2
NYU:
  ip_addresses:
    - 127.0.0.3
NYUSH:
  ip_addresses:
    - 127.0.0.4
NYSID:
  ip_addresses:
    - 127.0.0.5
HSL:
  ip_addresses:
    - 127.0.0.6
CU:
  ip_addresses:
    - 127.0.0.7
NS:
  ip_addresses:
    - 127.0.0.8
<% end %>
# Default institution
BOBST:
  name: NYU Libraries' Affiliates
  views:
    css: application
    dir: nyu
    breadcrumbs:
      title: NYU Libraries
      url: http://library.nyu.edu
    login:
      name: Other Borrowers
      primary: aleph
      secondary:
        - nyu
        - ns
        - cu
        - nysid
