# Private institutional settings
# <%= Figs.env.institutions.to_yaml if Figs.env.respond_to?(:institutions)%>
BOBST:
  name: NYU Libraries' Affiliates
  views:
    css: application
    dir: nyu
    breadcrumbs:
      title: NYU Libraries
      url: http://library.nyu.edu
    login:
      primary: aleph
      secondary:
        - nyu
        - ns
        - cu
        - nysid
