#!/bin/sh -e

: "${ECR_DOMAIN?Must specify ECR_DOMAIN}"
IMAGE_NAME=login

docker tag $IMAGE_NAME $ECR_DOMAIN/$IMAGE_NAME:latest
docker push $ECR_DOMAIN/$IMAGE_NAME:latest
docker tag $IMAGE_NAME $ECR_DOMAIN/$IMAGE_NAME:${CIRCLE_BRANCH//\//_}
docker push $ECR_DOMAIN/$IMAGE_NAME:${CIRCLE_BRANCH//\//_}
docker tag $IMAGE_NAME $ECR_DOMAIN/$IMAGE_NAME:${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
docker push $ECR_DOMAIN/$IMAGE_NAME:${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
