---
http_interactions:
- request:
    method: post
    uri: https://collector.newrelic.com/agent_listener/14//get_redirect_host?marshal_format=json
    body:
      encoding: UTF-8
      string: "[]"
    headers:
      Content-Encoding:
      - identity
      Host:
      - collector.newrelic.com
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - NewRelic-RubyAgent/3.12.1.298 (ruby 2.3.4 x86_64-linux) zlib/1.2.8
      Content-Type:
      - application/octet-stream
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/plain
      Content-Length:
      - '133'
    body:
      encoding: UTF-8
      string: '{"exception":{"message":"Invalid license key, please contact support@newrelic.com","error_type":"NewRelic::Agent::LicenseException"}}'
    http_version: 
  recorded_at: Fri, 23 Jun 2017 15:53:16 GMT
recorded_with: VCR 2.9.3
